"""Box + gridline overlays for a slice (or slices) -- the pure-geometry
counterpart to api.py's point sampling and contours.py's contour extraction.

slice_grid() computes an overlay grid for each slice in the requested
geometry: an outer bounding box plus evenly-spaced horizontal and vertical
lines, each line a densely-sampled ordered point set suitable for
plotnine.geom_path(). slice_grid_layers() returns ready-made, composable
plotnine layers for the box and grid components, since they normally need
separate geom_path() calls with different styling.
"""

from __future__ import annotations

import numpy as np
import pandas as pd
from plotnine import aes, geom_path

from ._utils import check_sitk_image
from .api import _as_slice_package_set, build_slice_geometry
from .io import ReadImage_fix


def _seq_by(start, end, by):
    """Mirror R's seq(from=start, to=end, by=by): start, stepping by `by`,
    stopping at the largest value not exceeding `end`.
    """
    n = int(np.floor((end - start) / by + 1e-9))
    return start + np.arange(n + 1) * by


def _resolve_geometry_only(image, axis, coordinate, geometry):
    """Resolve the shared geometry/axis/coordinate arguments for
    slice_grid(), which (unlike slice_image()/slice_contours()) needs no
    image sampling at all -- `image` exists only to feed
    build_slice_geometry() when `geometry` isn't supplied directly.
    """
    has_geometry = geometry is not None
    if has_geometry and (axis is not None or coordinate is not None):
        raise ValueError("axis/coordinate must not be supplied together with geometry.")
    if not has_geometry and (axis is None or coordinate is None):
        raise ValueError("Provide either geometry, or both axis and coordinate.")
    if has_geometry:
        return _as_slice_package_set(geometry)
    if image is None:
        raise ValueError("image is required when geometry is not supplied.")
    if isinstance(image, str):
        image = ReadImage_fix(image)
    check_sitk_image(image)
    return build_slice_geometry(image, axis, coordinate)


def _slice_grid_lines(slice_geom, spacing, point_spacing, padding):
    """Build every box/grid line for a single SliceGeometry, in local
    in-plane coordinates mapped to world space via that slice's own
    origin/direction_i/direction_j. Both box and grid lines are generated by
    the same code: the box is just 2 lines per axis, at the (padded)
    extremes.
    """
    extent = slice_geom.extent
    if np.any(extent + 2 * padding <= 0):
        raise ValueError("padding is too large (negative) relative to the slice's extent.")
    if spacing is None:
        spacing = float(np.min(extent)) / 10
    if point_spacing is None:
        point_spacing = spacing / 20

    origin = slice_geom.origin
    di = slice_geom.direction_i
    dj = slice_geom.direction_j

    def build_lines_for_axis(grid_axis, grid_coords, part):
        """Build one line (a DataFrame of points) per coordinate in
        `grid_coords`, each fixed at that coordinate along `grid_axis` and
        spanning the full (padded) extent of the other in-plane axis.
        """
        line_extent_len = extent[1] if grid_axis == "i" else extent[0]
        line_start = 0 - padding
        line_end = line_extent_len + padding
        n_line_pts = max(2, round((line_end - line_start) / point_spacing) + 1)
        line_coords = np.linspace(line_start, line_end, n_line_pts)

        frames = []
        for line_id, gc in enumerate(grid_coords, start=1):
            if grid_axis == "i":
                local_i = np.full(n_line_pts, gc)
                local_j = line_coords
            else:
                local_i = line_coords
                local_j = np.full(n_line_pts, gc)
            world = origin + np.outer(local_i, di) + np.outer(local_j, dj)
            frames.append(pd.DataFrame({
                "part": part, "grid_axis": grid_axis, "line_id": line_id,
                "vertex": np.arange(1, n_line_pts + 1),
                "x": world[:, 0], "y": world[:, 1], "z": world[:, 2],
            }))
        return pd.concat(frames, ignore_index=True)

    box_i_coords = [0 - padding, extent[0] + padding]
    box_j_coords = [0 - padding, extent[1] + padding]
    box = pd.concat([
        build_lines_for_axis("i", box_i_coords, "box"),
        build_lines_for_axis("j", box_j_coords, "box"),
    ], ignore_index=True)

    grid_i_coords = _seq_by(0 - padding, extent[0] + padding, spacing)
    grid_j_coords = _seq_by(0 - padding, extent[1] + padding, spacing)
    grid = pd.concat([
        build_lines_for_axis("i", grid_i_coords, "grid"),
        build_lines_for_axis("j", grid_j_coords, "grid"),
    ], ignore_index=True)

    return pd.concat([box, grid], ignore_index=True)


def slice_grid(image=None, axis=None, coordinate=None,
                spacing=None, point_spacing=None, padding=0, geometry=None):
    """Build a box + gridline overlay for a slice (or slices).

    Computes an overlay grid for each slice in the requested geometry: an
    outer bounding box plus evenly-spaced horizontal and vertical lines
    (same spacing in both directions), each line a densely-sampled ordered
    set of points suitable for `plotnine.geom_path()`. Typical uses: a
    visual reference grid over an anatomical slice, or (combined with
    `transform_points()`) a grid warped through a registration transform, to
    visualize what that transform does to the image.

    Unlike `slice_image()`/`slice_contours()`, no image is sampled here --
    the grid is pure geometry, computed entirely from the resolved
    SliceGeometry/SlicePackage/SlicePackageSet. `image` (with
    `axis`/`coordinate`) exists only for interface consistency with those
    functions, feeding `build_slice_geometry()` when `geometry` isn't
    supplied directly.

    Parameters
    ----------
    image : SimpleITK.Image or str, optional
        Required unless `geometry` is supplied.
    axis : int or str, optional
        Which image axis is out-of-plane (see `build_slice_geometry`).
        Required unless `geometry` is supplied; must not be supplied
        together with `geometry`.
    coordinate : float or array-like of float, optional
        See `build_slice_geometry`. Required unless `geometry` is supplied;
        must not be supplied together with `geometry`.
    spacing : float, optional
        Distance between adjacent gridlines, the same for both horizontal
        and vertical. Defaults (if None) to `min(extent) / 10`,
        scale-adaptive so it's reasonable whether the slice is measured in
        mm or µm.
    point_spacing : float, optional
        Distance between points along a single line, controlling how
        smooth/coarse it looks when plotted. Defaults (if None) to
        `spacing / 20`.
    padding : float, optional
        Extend (positive) or inset (negative) the box beyond the slice's
        true extent. Default 0 (exact bounds).
    geometry : SliceGeometry, SlicePackage, or SlicePackageSet, optional
        A pre-built geometry, used instead of `axis`/`coordinate`.

    Returns
    -------
    pandas.DataFrame
        Columns `package`, `k`, `part` ("box" or "grid"), `grid_axis` ("i"
        or "j": which in-plane axis is held fixed along this line),
        `line_id` (distinguishes different lines sharing the same
        `part`/`grid_axis`), `vertex` (1-based order within the line), `x`,
        `y`, `z` (world coordinates).
    """
    if spacing is not None and (not np.isscalar(spacing) or spacing <= 0):
        raise ValueError("spacing must be a single positive number (or None for the default).")
    if point_spacing is not None and (not np.isscalar(point_spacing) or point_spacing <= 0):
        raise ValueError("point_spacing must be a single positive number (or None for the default).")
    if not np.isscalar(padding):
        raise ValueError("padding must be a single number.")

    package_set = _resolve_geometry_only(image, axis, coordinate, geometry)

    frames = []
    for pkg_name, pkg in package_set.packages.items():
        for k in range(pkg.size_k):
            slice_geom = pkg.get_slice(k)
            lines = _slice_grid_lines(slice_geom, spacing, point_spacing, padding)
            lines.insert(0, "k", k)
            lines.insert(0, "package", pkg_name)
            frames.append(lines)

    out = pd.concat(frames, ignore_index=True)
    return out[["package", "k", "part", "grid_axis", "line_id", "vertex", "x", "y", "z"]]


def slice_grid_layers(grid_df,
                       box_color="orange", box_size=1, box_alpha=1,
                       grid_color="#FF6666", grid_size=0.25, grid_alpha=0.8):
    """Ready-made plotnine layers for a grid produced by slice_grid().

    slice_grid()'s box and grid lines are two visually-distinct components
    that normally need two separate geom_path() calls with different
    styling. This returns both as ready-made, composable layers to add to a
    plot, rather than requiring the user to filter `part` and write the
    grouping expression themselves.

    Parameters
    ----------
    grid_df : pandas.DataFrame
        As returned by `slice_grid()`.
    box_color, box_size, box_alpha : optional
        Style for the box layer.
    grid_color, grid_size, grid_alpha : optional
        Style for the grid layer.

    Returns
    -------
    dict
        Keys "box" and "grid", each a `plotnine.geom_path()` layer. Add both
        (e.g. `plt + layers["box"] + layers["grid"]`) to a plot that already
        maps x/y via its own `aes()`.
    """
    def _with_group_column(df_part):
        """Add a `_line_group` column identifying each distinct line, for
        `aes(group=...)` in the returned geom_path layer.
        """
        df_part = df_part.copy()
        df_part["_line_group"] = (
            df_part["package"].astype(str) + "|" +
            df_part["k"].astype(str) + "|" +
            df_part["grid_axis"].astype(str) + "|" +
            df_part["line_id"].astype(str)
        )
        return df_part

    box_layer = geom_path(
        data=_with_group_column(grid_df[grid_df["part"] == "box"]),
        mapping=aes(group="_line_group"),
        color=box_color, size=box_size, alpha=box_alpha,
    )
    grid_layer = geom_path(
        data=_with_group_column(grid_df[grid_df["part"] == "grid"]),
        mapping=aes(group="_line_group"),
        color=grid_color, size=grid_size, alpha=grid_alpha,
    )

    return {"box": box_layer, "grid": grid_layer}
